version: 2
registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{ github.actor }}
    password: ${{ secrets.HUB_ACCESS }}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
